repos:
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.27.0
    hooks:
    - id: yapf
      args: ["--style=google", "-i"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.740
    hooks:
    - id: mypy
      args: ["--ignore-missing-imports"]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: check-merge-conflict
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
    - id: flake8
      args: ["--ignore=E501,W504,E251,E266,E401,E126,E124"]
    - id: check-added-large-files
      args: ["--maxkb=2000"]